services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:               # defines the scalar arguments once and apply them to any service defined/created in this file

    Aldaflux\AldafluxIdsSanteBundle\Service\IdsUserSymfonyService:
        arguments: ["@parameter_bag", "@logger","@doctrine.orm.default_entity_manager","@security.token_storage","@request_stack","@event_dispatcher"]        
        tags:
            -
                name:     monolog.logger
                channel:       'ids'
    indaflux_ids_sante.user_symfony:
        alias: Aldaflux\AldafluxIdsSanteBundle\Service\IdsUserSymfonyService
        public: true        
        
    Aldaflux\AldafluxIdsSanteBundle\Controller\IdsRestController:
        tags:
            -
                name: 'controller.service_arguments'
            -
                name:     monolog.logger
                channel:       'ids'
        autoconfigure: true


        
    Aldaflux\AldafluxIdsSanteBundle\Controller\IdsLogsController:
        tags:
            -
                name: 'controller.service_arguments'
            -
                name:     monolog.logger
                channel:       'ids'
        autoconfigure: true


        
        
    Aldaflux\AldafluxIdsSanteBundle\Controller\IdsTestController:
        tags:
            -
                name: 'controller.service_arguments'
            -
                name:     monolog.logger
                channel:       'ids'
        autoconfigure: true


        
        
 
    Aldaflux\AldafluxIdsSanteBundle\Service\CheckPasswordService:
#        arguments: ["@parameter_bag", "@security.user_password_hasher", "@doctrine.orm.default_entity_manager", "@logger", "@indaflux_ids_sante.user_symfony"]
        tags:
            -
                name:     monolog.logger
                channel:       'ids'


    Aldaflux\AldafluxIdsSanteBundle\Service\ApiAuthentifiedService:
        tags:
            -
                name:     monolog.logger
                channel:       'ids'
                
    Aldaflux\AldafluxIdsSanteBundle\Service\IDSLog:
        tags:
            -
                name:     monolog.logger
                channel:       'ids.log'
                
                
    Aldaflux\AldafluxIdsSanteBundle\Service\IdsMainService:
        tags:
            -
                name:     monolog.logger
                channel:       'ids.log'
                
                
    indaflux_ids_sante.idslog:
        alias: Aldaflux\AldafluxIdsSanteBundle\Service\IDSLog
        public: true        

    Aldaflux\AldafluxIdsSanteBundle\DataCollector\IdsSanteCollector:
        arguments: ["@indaflux_ids_sante.idslog","@parameter_bag"]
#        arguments: ["@parameter_bag"]
        tags:
            -
                name:     data_collector
                id:       'aldaflux.ids_sante_collector'

    Aldaflux\AldafluxIdsSanteBundle\Command\TestUserCommand:
        arguments: ["@doctrine.orm.default_entity_manager","@parameter_bag", "@security.user_password_hasher", "@indaflux_ids_sante.user_symfony"]
        tags:
            -
                name:     console.command
                id:       'aldaflux.ids_user_test'


